# Default Values

replicaCount: 1
storage: 10Gi

image:
  repo: ghost

pod:
  port: 2368

nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  tier: Frontend
  type: LoadBalancer
  port: 2368
