apiVersion: v1
kind: Service
metadata:
  name: ghost-trans
  labels:
    app: ghost-trans
spec:
  ports:
    - port: 2368
  selector:
    app: ghost-trans
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ghost-trans
  labels:
    app: ghost-trans
spec:
  selector:
    matchLabels:
      app: ghost-trans
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost-trans
    spec:
      containers:
      - image: ghost:2.9.1
        name: ghost-trans
        ports:
        - containerPort: 2368
          name: ghost-trans
